### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by Keyros** [epeshk/ConcurrencyToolkit#7]
Some test periodically fail 
<img width="954" alt="Screenshot 2023-07-31 at 22 32 06" src="https://github.com/epeshk/ConcurrencyToolkit/assets/1851787/6d7424d0-e43d-4ad5-bec7-5243f52faedd">

PrioritySemaphoreTests.SemaphoreShouldLimitSyncConsumers
in cases where the limit is equal to the number of threads
the code may run faster than we expect and we will never set fullThroughputReached to true.
It seems to me that we can not test the case when the limit is equal to the number of threads

env:
<img width="1170" alt="Screenshot 2023-07-31 at 22 22 37" src="https://github.com/epeshk/ConcurrencyToolkit/assets/1851787/e7f5191c-c260-4cf6-abe2-cf76b639aa16">

**Comment by epeshk** [comment]
Fixed by https://github.com/epeshk/ConcurrencyToolkit/commit/dee99adfcddee5d29c4e348bf502f97c0d072867
